name: Keep Render free instance alive

on:
  schedule:

  # every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Render free instance alive
        run: |
          curl -X POST https://my-bitget-wallet-back.onrender.com/keep-alive